remote_theme: thuhcsi/slate
title: An End-to-End Approach for Chord-Conditioned Song Generation
description: Submitted to interspeech
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
